In [1]:
# Tensor : 배열과 비슷한 자료구조
# PyTorch에서는 Tensor를 이용하여 모델의 입력과 출력, 그리고 모델의 매개변수를 부호화함.
import torch
import numpy as np

# 직접 텐서 생성
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)


In [2]:
# Numpy배열로부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [3]:
# 다른 텐서로 생성
# 명시적으로 재정의(overriding)하지 않는다면 인자로 주어진 속성(모양(shape), 자료형(datatype))을 유지
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지
print(f"Ones Tensor: \n {x_ones} \n")

# rand_like 임의의 난수생성
x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씀.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8273, 0.1677],
        [0.4591, 0.8727]]) 



In [7]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.4074, 0.1637, 0.3903],
        [0.6146, 0.8396, 0.1431]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
tensor = torch.rand(3,4)

# 텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냄.
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [22]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1].shape}")

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: torch.Size([4])
