In [ ]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
# requires_grad를 사용하는 이유는 손실이 나왔을 때 미분으로 어느 방향으로 바꿀지 계산하기 위함이다.
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = x @ w + b
# 정답과 예측의 손실 계산
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
print(loss)

print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

tensor([[ 1.0667, -0.4047,  0.2412],
        [ 0.5510, -0.0741, -0.6062],
        [ 1.5943, -0.8437, -0.4471],
        [ 0.7140, -1.1538, -1.5740],
        [-0.9418, -0.7868, -0.4336]], requires_grad=True)
tensor(1.1209, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Gradient function for z = <AddBackward0 object at 0x000002075F4FAD10>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x000002075F4FAD10>


In [ ]:
# 손실 기반 역전파(미분 사용)
# 역전파 : 가중치를 어느 방향으로 바꿀지 계산
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.3201, 0.0221, 0.0215],
        [0.3201, 0.0221, 0.0215],
        [0.3201, 0.0221, 0.0215],
        [0.3201, 0.0221, 0.0215],
        [0.3201, 0.0221, 0.0215]])
tensor([[ 1.0667, -0.4047,  0.2412],
        [ 0.5510, -0.0741, -0.6062],
        [ 1.5943, -0.8437, -0.4471],
        [ 0.7140, -1.1538, -1.5740],
        [-0.9418, -0.7868, -0.4336]], requires_grad=True)
tensor([0.3201, 0.0221, 0.0215])


In [ ]:
z = x @ w + b
print(z.requires_grad)

# 학습된 모델에는 순전파만 필요하기 때문에 z tensor의 requires_grad를 지운다.
# 그러면 계산 속도가 향상된다.
with torch.no_grad():
  z = x @ w + b
print(z.requires_grad)

True
False
