In [2]:
import torch
import numpy as np

In [3]:
# initialize a tensor
# directly initialize from normal array
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
# initialize from numpy array
np_array = np.array(data)
x_np = torch.tensor(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9367, 0.8083],
        [0.2640, 0.0727]], dtype=torch.float64) 



In [6]:
# use a tuple to define the shape of a tensor
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

# pass argument directly to define the tensor shape
shape_tensor = torch.rand(2, 3)
print("shape_tensor", shape_tensor)

Random Tensor: 
 tensor([[0.1090, 0.4675, 0.8915],
        [0.9536, 0.9639, 0.6762]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
shape_tensor tensor([[0.5038, 0.9597, 0.8905],
        [0.7081, 0.0296, 0.8642]])


In [7]:
# describe tensor
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [19]:
# indexing slicing
tensor = torch.ones(4, 4)

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
# Ellipsis(...) selects all preceding dimensions
print(f"Last column: {tensor[..., -1]}")

# vectorize
tensor[:, 2] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


In [ ]:
# joining tensor along axis you want
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1.shape)
print(t1)

torch.Size([4, 12])
tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])


In [ ]:
# arithemtic tensor
y1 = tensor @ tensor.T
print(y1)

z1 = tensor * tensor.T
print(z1)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
<built-in method item of Tensor object at 0x0000020E48EE6120>


In [ ]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item)

tensor(12.)
tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])
12.0
