In [5]:
import torch
import numpy as np

In [6]:
# initialize a tensor
# directly initialize from normal array
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [7]:
# initialize from numpy array
np_array = np.array(data)
x_np = torch.tensor(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [8]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9847, 0.2162],
        [0.5489, 0.7352]], dtype=torch.float64) 



In [9]:
# use a tuple to define the shape of a tensor
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

# pass argument directly to define the tensor shape
shape_tensor = torch.rand(2, 3)
print("shape_tensor", shape_tensor)

Random Tensor: 
 tensor([[0.1961, 0.0179, 0.6136],
        [0.8318, 0.5586, 0.9772]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
shape_tensor tensor([[0.5681, 0.6744, 0.6420],
        [0.1930, 0.1852, 0.3571]])


In [10]:
# describe tensor
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [22]:
# indexing slicing
tensor = torch.ones(4, 4)

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
# Ellipsis(...) selects all preceding dimensions
print(f"Last column: {tensor[..., -1]}")

# vectorize
tensor[..., -1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


In [23]:
# joining tensor
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)


tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])
