In [83]:
# Tensor : 배열과 비슷한 자료구조
# PyTorch에서는 Tensor를 이용하여 모델의 입력과 출력, 그리고 모델의 매개변수를 부호화함.
import torch
import numpy as np

# 직접 텐서 생성
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)


In [84]:
# Numpy배열로부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [85]:
# 다른 텐서로 생성
# 명시적으로 재정의(overriding)하지 않는다면 인자로 주어진 속성(모양(shape), 자료형(datatype))을 유지
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지
print(f"Ones Tensor: \n {x_ones} \n")

# rand_like 임의의 난수생성
x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씀.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4348, 0.3741],
        [0.6967, 0.2325]]) 



In [86]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.5085, 0.1278, 0.0115],
        [0.5173, 0.1275, 0.2086]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [87]:
tensor = torch.rand(3,4)

# 텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냄.
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [88]:
# GPU가 존재하면 텐서를 이동
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

tensor = torch.ones(4, 4)
# :은 전체 인덱스를 표시
# [:] 0번째 차원의 전체 인덱스
# [:, 0] 0번째 차원 전체, 1번째 차원의 0번 인덱스를 모아 새로운 배열
# ...은 앞의 명시하지 않은 나머지 모든 차원 - 쓰지 않은 나머지 차원들을 자동으로 : 처리
# [..., 1] 앞의 모든 차원 유지, 마지막 차원의 1번 인덱스를 모아 새로운 배열
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

# 백터화 : 어떤 자료구조를 반복문 없이 전체 데이터를 한 번에 계산하는 기법/방식
# Tensor의 다차원 배열구조는 벡터화 가능!
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# 괄호 0겹 → 0차원 → tensor(5)
# 괄호 1겹 → 1차원 → tensor([1,2,3])
# 괄호 2겹 → 2차원 → tensor([[1,2],[3,4]])
# 괄호 3겹 → 3차원 → tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
# dim=0은 차원이 아니라 축으로 생각하자
# torch.cat([tensor, tensor, tensor], dim=1])에서 dim=1은
# 1번째 축을 합친다는 것이다.
# 현재 텐서의 shape는 [4,4]이므로 [4,12]이 되는 것이다.
# shape: [1, 2, 3]
#         ↑  ↑  ↑
#     0번축 1번축 2번축의 크기
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [90]:
# @ : 행렬곱 - 앞 행렬의 행과 뒤 행렬의 열을 내적을 반복하여 새로운 행렬을 만드는 연산 - (n * p) @ (p * m) = (n, m)
# 내적 : 성분끼리 곱해서 모두 더한 값(벡터끼리의 연산이라 보면 됨.)
# 쉽게 말해 앞의 행과 뒤의 열의 각 인덱스를 곱한 뒤 다 더하면 된다. [a₁, a₂, a₃] · [b₁, b₂, b₃] = a₁b₁ + a₂b₂ + a₃b₃
# 다만 (n * p) @ (p * m) = (n, m)의 형태는 지킬 것
# T : 전치행렬(Transpose) - 행과 열을 서로 뒤바꾼 행렬 (2 * 3) -> (3 * 2)
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)

# 요소곱
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(f"{z1} \n {z2}")  

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [91]:
# sum() : 모든 요소의 값을 하나로 집계(모두 더함)
agg = tensor.sum()
print(agg)
# 요소가 하나일 땐 Python숫자값으로 변경 가능
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


In [92]:
# In-place 연산은 자동 미분(autograd) 추적에 문제를 일으킬 수 있음
# tensor += 5  # 비추천
# tensor.add_(5)  # 비추천

# 새 텐서를 생성하는 방식 사용
tensor = tensor + 5  # 추천
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
